using System.Collections.Generic;
namespace Zenith.Mac;
internal static class EnglishResources
{
    public static readonly Dictionary<string, string> Values = new()
    {
        ["LanguageName"] = "English",
        ["generalTab"] = "General",
        ["modulesTab"] = "Modules",
        ["moduleSettingsTab"] = "Module Settings",
        ["renderTab"] = "Render",
        ["updateDownloading"] = "Downloading update...",
        ["updateReady"] = "Update installed!",
        ["clickToRestart"] = "Click here to restart Zenith",
        ["load"] = "Load",
        ["unload"] = "Unload",
        ["width"] = "Width",
        ["height"] = "Height",
        ["browse"] = "Browse",
        ["fps"] = "FPS",
        ["presets"] = "Presets",
        ["zenithRenderWarning"] = "Warning: Zenith Preview renders in the resolution above, then downscales to the window size",
        ["superRes"] = "SSAA",
        ["superResWarning"] = "Increasing SSAA can greatly increase the smoothness of the pixels but takes much more performance",
        ["language"] = "Language",
        ["renderResolution"] = "Render Resolution",
        ["previewOptions"] = "Preview Options",
        ["renderOptions"] = "Render Options",
        ["reload"] = "Reload",
        ["startPreview"] = "Start Preview",
        ["stop"] = "Stop",
        ["vsync"] = "V-Sync Enabled",
        ["tempo"] = "Tempo Multiplier",
        ["pauseHint"] = "Right click slider or press space to toggle pause",
        ["paused"] = "Preview Paused",
        ["savePath"] = "Save Path",
        ["includeAudio"] = "Include Audio",
        ["renderMask"] = "Render Transparency Mask",
        ["bitrate"] = "Bitrate",
        ["crfHint"] = "FFMPEG crf: 0 = lossless, 51 = worst quality possible",
        ["delatStart"] = "Delay start (seconds)",
        ["ffmpegDebug"] = "ffmpeg debug",
        ["startRender"] = "Start Render",
        ["ifUploading"] = "If uploading the video online, please credit the program",
        ["Custom"] = "Customize FFmpeg Options (for experts, at your own risk)",
        ["realtimePlayback"] = "Realtime Playback",
        ["disableKDMAPI"] = "Disable KDMAPI",
        ["enableKDMAPI"] = "Enable KDMAPI",
        ["noteSize"] = "Note Size",
        ["tickBased"] = "Tick Based",
        ["timeBased"] = "Time Based",
        ["ignoreColorEvents"] = "Ignore Color Events",
        ["useBackgroundImage"] = "Use Background",
        ["pauseHintNew"] = "Press space to toggle pause, press enter on the preview window to fullscreen",
        ["palettes_reload"] = "Reload",
        ["palettes_new"] = "New",
        ["palettes_edit"] = "Edit",
        ["palettes_randomise"] = "Randomise color order",
        ["palettes_openFolder"] = "Open Palettes Folder",
        ["resourcesTab"] = "Resources",
        ["miscTab"] = "Misc",
        ["settingsTab"] = "Script Settings",
        ["resourcePath"] = "Resource packs path:",
        ["resourcePathDir"] = "Plugins\\Assets\\Textured\\Resources",
        ["openFolder"] = "Open Folder",
        ["reloadList"] = "Reload List",
        ["reloadScript"] = "Reload Script",
        ["firstNote"] = "First Note",
        ["lastNote"] = "Last Note",
        ["noteScreenTime"] = "Note screen time",
        ["profile"] = "Profile",
        ["save"] = "Save",
        ["delete"] = "Delete",
        ["defaults"] = "Defaults",
    };
}
