<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><ApplicationManifest>app.manifest</ApplicationManifest><AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault></PropertyGroup><ItemGroup><PackageReference Include="Avalonia" Version="11.3.9" /><PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.3.9" /><PackageReference Include="Avalonia.Desktop" Version="11.3.9" /><PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" /><PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.9" /><ProjectReference Include="../Zenith.Core/Zenith.Core.csproj" /></ItemGroup><ItemGroup><AvaloniaResource Include="Assets/**" /></ItemGroup></Project>
